# backend/Dockerfile

FROM python:3.8-slim

# Instalar ping
RUN apt-get update && apt-get install -y iputils-ping

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]
